fos_comment:
    db_driver: orm
    class:
        model:
            comment: App\Application\Sonata\CommentBundle\Entity\Comment
            thread: App\Application\Sonata\CommentBundle\Entity\Thread
    form:
        comment:
            type: sonata_comment_comment