jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            fos_user:
                path: '%kernel.root_dir%/../vendor/sonata-project/user-bundle/src/Resources/config/serializer'
                namespace_prefix: 'FOS\UserBundle'
            ecommerce_component:
                path: '%kernel.root_dir%/../vendor/sonata-project/ecommerce/src/BasketBundle/Resources/config/serializer/Component'
                namespace_prefix: 'Sonata\Component\Basket'
            #datagrid_bundle:
            #    path: '%kernel.root_dir%/../vendor/sonata-project/datagrid-bundle/Resources/config/serializer'
            #    namespace_prefix: 'Sonata\DatagridBundle'
            ApplicationSonataNewsBundle:
                namespace_prefix: 'Application\Sonata\NewsBundle\'
                path: '@ApplicationSonataNewsBundle/Resources/config/serializer'