# 
# more information can be found here http://sonata-project.org/bundles/news
#
sonata_news:
    title:        '%sonata_news.blog_title%'
    link:         '%sonata_news.blog_link%'
    description:  '%sonata_news.blog_description%'
    salt:         '%sonata_news.salt%'
    db_driver:    'doctrine_orm' # doctrine_orm or doctrine_mongodb it is mandatory to choose one here

    # permalink_generator: sonata.news.permalink.category # /party/new-year
    permalink_generator: sonata.news.permalink.date # /2011/12/31/new-year

    # comment options
    comment:
        notification:
            emails:   '%sonata_news.comment.emails%'
            from:     '%sonata_news.comment.email_from%'
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

    class:
        post:       App\Application\Sonata\NewsBundle\Entity\Post
        comment:    App\Application\Sonata\NewsBundle\Entity\Comment
        media:      App\Application\Sonata\MediaBundle\Entity\Media
        user:       App\Application\Sonata\UserBundle\Entity\User
        tag:        App\Application\Sonata\ClassificationBundle\Entity\Tag
        collection: App\Application\Sonata\ClassificationBundle\Entity\Collection