sonata_order:
    class:
        order:          App\Application\Sonata\OrderBundle\Entity\Order
        order_element:  App\Application\Sonata\OrderBundle\Entity\OrderElement
        customer:       App\Application\Sonata\CustomerBundle\Entity\Customer