sonata_delivery:
    methods:
        free: ~
        take_away: application.sonata.delivery.take_away

    services:
        free_address_required:
            name: Free
            priority: 1
            code: free

    selector: sonata.delivery.selector.default