sonata_basket:
    builder:            sonata.basket.builder.standard
    factory:            sonata.basket.entity.factory
    loader:             sonata.basket.loader.standard

    class:
        basket:         App\Application\Sonata\BasketBundle\Entity\Basket
        basket_element: App\Application\Sonata\BasketBundle\Entity\BasketElement
        customer:       App\Application\Sonata\CustomerBundle\Entity\Customer

    # Forms
    basket:
        form:
            type:       sonata_basket_basket
            name:       sonata_basket_basket_form
    shipping:
        form:
            type:       sonata_basket_shipping
            name:       sonata_basket_shipping_form
    payment:
        form:
            type:       sonata_basket_payment
            name:       sonata_basket_payment_form