sonata_product:
    products:
        # Goodies
        sonata.ecommerce_demo.product.goodie:
            provider: sonata.ecommerce_demo.product.goodie.type
            manager:  sonata.ecommerce_demo.product.goodie.manager

        # Travel
        sonata.ecommerce_demo.product.travel:
            provider: sonata.ecommerce_demo.product.travel.type
            manager: sonata.ecommerce_demo.product.travel.manager
            variations:
                fields: [travellers, travelDays, sku, slug, name, price, stock, vatRate, priceIncludingVat, enabled]

    seo:
        product:
            site: '@sonataproject'
            creator: '@th0masr'
            domain: 'http://demo.sonata-project.org'
            media_prefix: 'http://demo.sonata-project.org'
            media_format: 'reference'

    class:
        product:              App\Application\Sonata\ProductBundle\Entity\Product
        package:              App\Application\Sonata\ProductBundle\Entity\Package
        product_category:     App\Application\Sonata\ProductBundle\Entity\ProductCategory
        product_collection:   App\Application\Sonata\ProductBundle\Entity\ProductCollection
        category:             App\Application\Sonata\ClassificationBundle\Entity\Category
        collection:           App\Application\Sonata\ClassificationBundle\Entity\Collection
        delivery:             App\Application\Sonata\ProductBundle\Entity\Delivery
        gallery:              App\Application\Sonata\MediaBundle\Entity\Gallery
        media:                App\Application\Sonata\MediaBundle\Entity\Media