sonata_invoice:
    class:
        invoice:              App\Application\Sonata\InvoiceBundle\Entity\Invoice
        invoice_element:      App\Application\Sonata\InvoiceBundle\Entity\InvoiceElement
        order_element:        App\Application\Sonata\OrderBundle\Entity\OrderElement
        customer:             App\Application\Sonata\CustomerBundle\Entity\Customer