sonata_customer:
    class:
        customer:           App\Application\Sonata\CustomerBundle\Entity\Customer
        address:            App\Application\Sonata\CustomerBundle\Entity\Address
        order:              App\Application\Sonata\OrderBundle\Entity\Order
        user:               App\Application\Sonata\UserBundle\Entity\User

        customer_selector:  Sonata\Component\Customer\CustomerSelector