<?php

namespace App\Application\Sonata\PaymentBundle\Entity;

use Sonata\PaymentBundle\Entity\BaseTransaction as BaseTransaction;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html#working-with-objects
 */
class Transaction extends BaseTransaction
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
}
