# Enable Doctrine to map the provided entities
sonata_customer:
    profile:
        template:       'SonataCustomerBundle:Profile:action.html.twig'
        menu_builder:   'sonata.customer.profile.menu_builder.default'
        menu:
            -
                route: 'sonata_customer_dashboard'
                label: 'link_list_dashboard'
                domain: 'SonataCustomerBundle'
                route_parameters:  {}
            -
                route: 'fos_user_profile_edit'
                label: 'link_edit_profile'
                domain: 'SonataUserBundle'
                route_parameters:  {}
            -
                route: 'fos_user_change_password'
                label: 'sonata_change_password_link'
                domain: 'SonataUserBundle'
                route_parameters:  {}
            -
                route: 'sonata_customer_addresses'
                label: 'link_list_addresses'
                domain: 'SonataCustomerBundle'
                route_parameters:  {}
            -
                route:  'sonata_order_index'
                label:  'order_list'
                domain: 'SonataOrderBundle'
                route_parameters:  {}

        blocks:
            #- { position: left, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> <p>This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!</p>"} }
            #- { position: right, type: sonata.timeline.block.timeline, settings: { max_per_page: 15 }}
            -
                position: left
                type: sonata.order.block.recent_orders
                settings:
                    title: Recent Orders
                    number: 5
                    mode: public
            -
                position: right
                type: sonata.news.block.recent_posts
                settings:
                    title: Recent Posts
                    number: 5
                    mode: public
            -
                position: right
                type: sonata.news.block.recent_comments
                settings:
                    title: Recent Comments
                    number: 5
                    mode: public
    class:
        customer: AppBundle\Entity\Commerce\Customer
        address:  AppBundle\Entity\Commerce\Address
        order:    AppBundle\Entity\Commerce\Order
        user:     AppBundle\Entity\User\User

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataCustomerBundle: ~
