# sonata front controller
sonata_demo:
  resource: "@SonataDemoBundle/Resources/config/routing/demo.xml"

sonata_qa:
  resource: "@SonataQABundle/Resources/config/routing/qa.xml"

_monitor:
  resource: "@LiipMonitorBundle/Resources/config/routing.xml"
  prefix: /monitor/health

fos_comment:
  type: rest
  resource: "@FOSCommentBundle/Resources/config/routing.yml"
  prefix: /comments
  defaults: { _format: html }

sonata_cache_cache:
  resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
  prefix: /